theme: jekyll-theme-slate

title: Lin Hall
email: lehwx87@gmail.com
description: Lin is a recent Master of Science in Data Science graduate from East Carolina University. His interests include machine learning, optimization, and leveraging data to make decisions for real world applications.
