theme: jekyll-theme-slate

title: Lin Hall
email: lehwx87@gmail.com
description: Master of Science in Data Science graduate from East Carolina University. Interests include machine learning, optimization, and leveraging data to make decisions for real world applications.

social_links:
  github:  jekyll
  linkedin: jekyll
